//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("EstimationApp.Test")]
namespace EstimationApp.Localization
{
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EstimationApp.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string strUsername
        {
            get
            {
                return ResourceManager.GetString("strUsername", resourceCulture);
            }
        }

        internal static string strPassword
        {
            get
            {
                return ResourceManager.GetString("strPassword", resourceCulture);
            }
        }

        internal static string strLogin
        {
            get
            {
                return ResourceManager.GetString("strLogin", resourceCulture);
            }
        }

        internal static string strCancel
        {
            get
            {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }

        internal static string strOK
        {
            get
            {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }

        internal static string strGoldPricePerGram
        {
            get
            {
                return ResourceManager.GetString("strGoldPricePerGram", resourceCulture);
            }
        }

        internal static string strWeightInGrams
        {
            get
            {
                return ResourceManager.GetString("strWeightInGrams", resourceCulture);
            }
        }

        internal static string strTotalPrice
        {
            get
            {
                return ResourceManager.GetString("strTotalPrice", resourceCulture);
            }
        }

        internal static string strDiscountInPercentange
        {
            get
            {
                return ResourceManager.GetString("strDiscountInPercentange", resourceCulture);
            }
        }

        internal static string strCalculate
        {
            get
            {
                return ResourceManager.GetString("strCalculate", resourceCulture);
            }
        }

        internal static string strPrintToScreen
        {
            get
            {
                return ResourceManager.GetString("strPrintToScreen", resourceCulture);
            }
        }

        internal static string strPrintToFile
        {
            get
            {
                return ResourceManager.GetString("strPrintToFile", resourceCulture);
            }
        }

        internal static string strPrintToPaper
        {
            get
            {
                return ResourceManager.GetString("strPrintToPaper", resourceCulture);
            }
        }

        internal static string strClose
        {
            get
            {
                return ResourceManager.GetString("strClose", resourceCulture);
            }
        }

        internal static string strLogout
        {
            get
            {
                return ResourceManager.GetString("strLogout", resourceCulture);
            }
        }

        internal static string strAlert
        {
            get
            {
                return ResourceManager.GetString("strAlert", resourceCulture);
            }
        }

        internal static string alertUsernamePasswordRequired
        {
            get
            {
                return ResourceManager.GetString("alertUsernamePasswordRequired", resourceCulture);
            }
        }

        internal static string alertWrongUsernameOrPassword
        {
            get
            {
                return ResourceManager.GetString("alertWrongUsernameOrPassword", resourceCulture);
            }
        }

        internal static string alertSuccess
        {
            get
            {
                return ResourceManager.GetString("alertSuccess", resourceCulture);
            }
        }

        internal static string alertGeneralErrorMessage
        {
            get
            {
                return ResourceManager.GetString("alertGeneralErrorMessage", resourceCulture);
            }
        }

        internal static string alertLogoutMessage
        {
            get
            {
                return ResourceManager.GetString("alertLogoutMessage", resourceCulture);
            }
        }

        internal static string alertCancelLogin
        {
            get
            {
                return ResourceManager.GetString("alertCancelLogin", resourceCulture);
            }
        }

        internal static string strSelectPrinterType
        {
            get
            {
                return ResourceManager.GetString("strSelectPrinterType", resourceCulture);
            }
        }

        internal static string strPrintText
        {
            get
            {
                return ResourceManager.GetString("strPrintText", resourceCulture);
            }
        }

        internal static string strDone
        {
            get
            {
                return ResourceManager.GetString("strDone", resourceCulture);
            }
        }

        internal static string strExit
        {
            get
            {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }

        internal static string strProceedWithYourLogin
        {
            get
            {
                return ResourceManager.GetString("strProceedWithYourLogin", resourceCulture);
            }
        }

        internal static string strCopyrightText
        {
            get
            {
                return ResourceManager.GetString("strCopyrightText", resourceCulture);
            }
        }
    }
}
